Repository chromebrew/chromebrew, pull requests merged in 2020-10, with the labels that each got.

#4365 Update OpenSSH to 8.4p1, fix configure error
  packages/openssh.rb
Labels: hacktoberfest

#4372 Update nftables from 0.9.0 to 0.9.6
  packages/libnftnl.rb
  packages/nftables.rb
Labels: hacktoberfest

#4375 libdrm update to 2.4.102, adjusted for meson build
  packages/libdrm.rb
Labels: hacktoberfest-accepted

#4392 Update core packages cmake, curl, git, libressl, meson, python3 and ruby
  install.sh
  packages/cmake.rb
  packages/curl.rb
  packages/git.rb
  packages/libressl.rb
  packages/meson.rb
  packages/python3.rb
  packages/ruby.rb
  tools/core_packages.txt
Labels: high priority

#4436 [zathura] Update to 0.4.7
  packages/zathura.rb
Labels: hacktoberfest-accepted

#4435 [ansible] Update to 2.9.14
  packages/ansible.rb
Labels: hacktoberfest-accepted

#4437 [poppler] Update to 20.10.0
  packages/poppler.rb
Labels: hacktoberfest-accepted

#4438 [girara] Update to 0.3.5
  packages/girara.rb
Labels: hacktoberfest-accepted

#4442 [nginx] Update to 1.19.3
  packages/nginx.rb
Labels: hacktoberfest-accepted

#4441 [fzf] Update to 0.23.1
  packages/fzf.rb
Labels: hacktoberfest-accepted

#4468 Add compatibility 'all' to vulkan_icd_loader
  packages/vulkan_icd_loader.rb
Labels: high priority

#4472 pcre2 update to 10.35
  packages/pcre2.rb
Labels: hacktoberfest-accepted

#4471 R update to 4.0.3
  packages/r.rb
Labels: hacktoberfest-accepted

#4465 Vala Update to 0.50.1
  packages/vala.rb
Labels: hacktoberfest-accepted

#4453 xdmcp update to 1.1.3 , use clang
  packages/libxdmcp.rb
Labels: hacktoberfest-accepted

#4422 Update codium from 1.49.2 to 1.50.1
  packages/codium.rb
Labels: hacktoberfest-accepted

#4433 Update gcc_tools from 1.0 to 1.1 and add gcc10 option
  packages/gcc10.rb
  packages/gcc_tools.rb
Labels: hacktoberfest-accepted

#4444 Update texlive from 2017 to 20201017
  packages/texlive.rb
Labels: hacktoberfest-accepted

#4445 Add appstream_glib package and dependencies
  packages/appstream_glib.rb
  packages/libstemmer.rb
  packages/libyaml.rb
  tools/packages.yaml
Labels: hacktoberfest-accepted

#4446 Update libarchive from 3.4.2 to 3.4.3
  packages/libarchive.rb
Labels: hacktoberfest-accepted

#4473 [firefox] Update to 82.0
  packages/apulse.rb
  packages/firefox.rb
Labels: hacktoberfest-accepted

#4482 Added instructions and all-in-one script to use i3 windows manager
  packages/i3.rb
Labels: hacktoberfest-accepted

#4485 Add pre-built binaries for packages a-z
  packages/apulse.rb
  packages/glmark2.rb
  packages/glslang.rb
  packages/graphite.rb
  packages/libxdmcp.rb
  packages/mpv.rb
  packages/pcre2.rb
  packages/r.rb
  packages/vala.rb
  packages/vulkan_headers.rb
  packages/vulkan_icd_loader.rb
  packages/xorg_proto.rb
  packages/zathura.rb
  tools/needs_binaries.sh
  tools/packages.yaml
Labels: hacktoberfest-accepted

#4478 Use builtin curl & have curl retry downloads
  crew
Labels: hacktoberfest-accepted

#4483 Add logic for virtualized building of armv7l
  lib/const.rb
Labels: hacktoberfest-accepted

#4484 Add CREW_CMAKE_OPTIONS & CREW_MESON_OPTIONS constants
  crew
  lib/const.rb
Labels: hacktoberfest-accepted

#4487 Rust update to 1.47.0 & minimal profile
  packages/rust.rb
Labels: hacktoberfest-accepted

#4460 libxrandr update to 1.5.2, use clang linker
  packages/libxrandr.rb
Labels: hacktoberfest-accepted

#4467 libRsvg Update to 2.50.1
  packages/librsvg.rb
Labels: hacktoberfest-accepted

#4492 Libxrandr has a libxext dependency.
  packages/libxrandr.rb
Labels: hacktoberfest-accepted

#4470 mesa update to 20.2.1, use gcc10 for building
  packages/mesa.rb
Labels: hacktoberfest-accepted

#4488 Add adwaita_icon_theme
  packages/adwaita_icon_theme.rb
Labels: hacktoberfest-accepted

#4455 Libxext Update to 1.3.4, use clang linker
  packages/libxext.rb
Labels: hacktoberfest-accepted

#4454 libx11 Update to 1.6.12, use clang linker
  packages/libx11.rb
Labels: hacktoberfest-accepted

#4456 Harfbuzz update to 2.7.2, use meson
  packages/harfbuzz.rb
Labels: hacktoberfest-accepted

#4459 Pixman Update to 0.40.0, use clang linker
  packages/pixman.rb
Labels: hacktoberfest-accepted

#4461 Pango update to 1.47, use clang linker
  packages/pango.rb
Labels: hacktoberfest-accepted

#4457 Libxrandr update to 1.5.2, use clang linker
  packages/libxrandr.rb
Labels: hacktoberfest-accepted

#4490 Gtk3: clang doesn't guarantee lld, so just use lld
  packages/gtk3.rb
Labels: hacktoberfest-accepted

#4501 librsvg: Fix CREW_OPTIONS breakage
  packages/librsvg.rb
Labels: hacktoberfest-accepted

#4500 Pango: Fix meson breakage
  packages/pango.rb
Labels: hacktoberfest-accepted

#4499 Mesa: Fix Meson_options breakage
  packages/mesa.rb
Labels: hacktoberfest-accepted

#4498 harfbuzz: Fix MESON_OPTIONS breakage
  packages/harfbuzz.rb
Labels: hacktoberfest-accepted

#4497 gtk3: fix library location
  packages/gtk3.rb
Labels: hacktoberfest-accepted

#4458 Libva update to 2.9.0, use clang
  packages/libva.rb
Labels: hacktoberfest-accepted

#4491 Update Opera to 72.0.3815.148
  packages/opera.rb
Labels: hacktoberfest-accepted

#4534 add xdpyinfo
  packages/xdpyinfo.rb
Labels: hacktoberfest-accepted

#4535 libunwind: Fix GCC10 compilation & update to 1.3.2
  packages/libunwind.rb
Labels: hacktoberfest-accepted

#4530 Add peg
  packages/peg.rb
Labels: hacktoberfest-accepted

#4541 Add missing libpsl and zstd dependencies
  crew
  install.sh
  lib/const.rb
  packages/buildessential.rb
  packages/git.rb
  tools/core_packages.txt
Labels: high priority
