Repository chromebrew/chromebrew, pull requests merged in 2021-02, with the labels that each got.

#5067 Update libarchive to fix @_ver line
  packages/libarchive.rb
Labels: high priority

#5096 Use valid ruby in inetutils.rb package
  packages/inetutils.rb
Labels: bug, high priority

#5114 Fix docbook_412.rb filename
  packages/docbook_xml412.rb
Labels: bug, high priority

#5122 install.sh: don't fail on chown of missing folders in /usr/local
  install.sh
Labels: high priority, installation

#5125 Remove redundant lines in install.sh for i686
  install.sh
Labels: high priority

#5130 Add krb5 to EARLY_PACKAGES
  install.sh
  packages/krb5.rb
Labels: bug, high priority, installation

#5131 install.sh: Add more early packages
  install.sh
Labels: high priority

#5272 prevent circular dependency hell from mono dep
  packages/avahi.rb
Labels: bug, high priority
