Repository chromebrew/chromebrew, pull requests merged in 2021-12, with the labels that each got.

#6428 upx: Fix compression on i686 with older kernels
  packages/upx.rb
Labels: bug, i686, high priority

#6309 cmake => 3.22.1, librhash => 1.4.2, libuv => 1.42.0, jsoncpp => 1.9.4
  packages/cmake.rb
  packages/jsoncpp.rb
  packages/librhash.rb
  packages/libuv.rb
Labels: hacktoberfest

#6514 Add fallback during install if rsync is not working
  bin/crew
  lib/const.rb
Labels: bug, high priority, regression

#6187 js91
  packages/gjs.rb
  packages/js91.rb
  packages/polkit.rb
Labels: i686

#6537 Revert #6495
  lib/const.rb
  lib/package.rb
Labels: high priority

#6540 packages.rb: Fix build errors
  lib/package.rb
Labels: bug, high priority

#6543 package.rb: Escape some bash special characters being passed to bash via system to fix issues with building.
  lib/package.rb
Labels: bug
