Repository chromebrew/chromebrew, pull requests merged in 2021-09, with the labels that each got.

#6222 Add GNU time binary
  packages/gnu_time.rb
Labels: please review

#6224 Connected updates & rebuilds of chafa, graphite, freetype, freetype_sub
  packages/chafa.rb
  packages/freetype.rb
  packages/freetype_sub.rb
  packages/graphite.rb
  packages/harfbuzz.rb
Labels: i686, build needed

#6232 pango needed rebuild for harfbuzz
  packages/pango.rb
Labels: i686, build needed

#6230 neon update to 0.32.1
  packages/neon.rb
Labels: i686, build needed

#6227 elfutils update and binutils rebuild
  packages/binutils.rb
  packages/elfutils.rb
Labels: please review

#5981 Inetutils -> 2.2
  packages/inetutils.rb
Labels: please review

#6238 llvm: 12.0.1 rebuild with newer icu4c for i686
  packages/llvm.rb
Labels: please review

#6018 gdb -> 11.1
  packages/gdb.rb
Labels: please review, i686

#6223 Mesa -> 21.2.2
  packages/mesa.rb
Labels: i686, build needed

#6178 Rust -> 1.55.0
  packages/rust.rb
Labels: please review

#6065 Static Musl Curl -> 7.79.1
  packages/curl.rb
Labels: please review

#6062 Musl native toolchain + all packages necessary for static curl, git builds
  packages/musl_brotli.rb
  packages/musl_c_ares.rb
  packages/musl_cyrus_sasl.rb
  packages/musl_expat.rb
  packages/musl_krb5.rb
  packages/musl_libidn2.rb
  packages/musl_libnghttp2.rb
  packages/musl_libssh.rb
  packages/musl_libunistring.rb
  packages/musl_lz4.rb
  packages/musl_native_toolchain.rb
  packages/musl_ncurses.rb
  packages/musl_openssl.rb
  packages/musl_xz.rb
  packages/musl_zlib.rb
  packages/musl_zstd.rb
Labels: please review

#6252 libnghttp2 -> 1.45.1, libcurl -> 7.79.1
  packages/libcurl.rb
  packages/libnghttp2.rb
Labels: i686, build needed

#6256 Fix syntax error, unexpected ',', expecting 'end' in libnghttp2
  packages/libnghttp2.rb
Labels: high priority

#6007 Add gcc 11.2.0 and libssp 11.2.0
  packages/gcc11.rb
  packages/libssp.rb
Labels: please review

#6261 libxml2 needs gcc11 dep for installs to succeed
  packages/buildessential.rb
  packages/core.rb
  packages/libxml2.rb
  tools/core_packages.txt
Labels: bug

#6034 Update OpenSSL perl modules
  packages/perl_io_socket_ssl.rb
  packages/perl_mozilla_ca.rb
  packages/perl_net_ssleay.rb
Labels: i686, build needed
