Repository chromebrew/chromebrew, pull requests merged in 2021-11, with the labels that each got.

#6310 new package bsdfetch
  packages/fetch.rb
  packages/go_fetch.rb
Labels: hacktoberfest

#6362 Actually fix the i686 hash for lzip binary.
  packages/lzip.rb
Labels: i686, high priority, installation

#6380 crew: fix typo (missing ?)
  bin/crew
  lib/const.rb
Labels: bug, high priority

#6395 rsync: fix missing runtime dependency
  packages/rsync.rb
Labels: bug

#6419 fix Keepassxc url
  packages/keepassxc.rb
Labels: bug

#6273 crew: Add `autoremove` command
  README.md
  bin/crew
  lib/const.rb
  lib/package.rb
Labels: hacktoberfest
