Repository chromebrew/chromebrew, pull requests merged in 2021-04, with the labels that each got.

#5553 Fix Wine package ternary operator line issue
  packages/wine.rb
Labels: high priority

#5563 fix png/gdk_pixbuf dep loop
  packages/gdk_pixbuf.rb
  packages/libavif.rb
  packages/libheif.rb
  packages/libpng.rb
  packages/libwmf.rb
Labels: high priority

#5574 Fix compatibility error for intel_media_driver
  packages/intel_media_driver.rb
Labels: high priority

#5581 Fix syntax error in gtk4
  packages/gtk4.rb
Labels: high priority

#5680 Fix glibc 2.27 binary_urls
  packages/glibc.rb
Labels: high priority

#5691 fix pipewire package typos.
  packages/pipewire.rb
Labels: bug, high priority

#5706 fix ocaml url
  packages/ocaml.rb
Labels: bug
