Repository chromebrew/chromebrew, pull requests merged in 2022-08, with the labels that each got.

#7306 ruby.rb: Delete `=` from `version`
  packages/ruby.rb
Labels: 🚨🚨 high priority 🚨🚨

#7341 Fix glibc symlinks not being made properly
  packages/glibc.rb
Labels: bug 🐛, installation 🔻

#7344 glibc: don't use ChromeOS version of libc.so
  packages/glibc.rb
Labels: bug 🐛
