Repository chromebrew/chromebrew, pull requests merged in 2022-10, with the labels that each got.

#7441 cargo_c -> 0.9.13
  packages/cargo_c.rb
Labels: hacktoberfest 🎃, hacktoberfest-accepted 🎃✔️

#7442 Edge 105.0.1343.42-1 => 105.0.1343.53-1
  packages/edge.rb
Labels: hacktoberfest-accepted 🎃✔️

#7443 Brave 1.43.93 => 1.44.105
  packages/brave.rb
Labels: hacktoberfest-accepted 🎃✔️

#7444 neovim -> 0.8.0
  packages/libvterm.rb
  packages/neovim.rb
Labels: hacktoberfest 🎃

#7447 llvm -> 15.0.1
  packages/llvm.rb
Labels: hacktoberfest 🎃

#7449 glibc: keep postinstall failures from breaking install
  packages/glibc.rb
Labels: hacktoberfest 🎃

#7451 Update datamash to 1.8 (NO BINARIES)
  packages/datamash.rb
Labels: hacktoberfest 🎃, hacktoberfest-accepted 🎃✔️

#7452 Actually upload the binaries for datamash and autoconf_archive
  packages/autoconf_archive.rb
  packages/datamash.rb
Labels: 🚨🚨 high priority 🚨🚨

#7453 Remove python 2 from core & buildessential, update doxygen -> 1.9.5
  packages/buildessential.rb
  packages/core.rb
  packages/doxygen.rb
  packages/glmark2.rb
  packages/komodo.rb
  packages/libewf.rb
  packages/py2_six.rb
  packages/q.rb
  packages/ranger.rb
  packages/scons.rb
  packages/smem.rb
  packages/weechat.rb
Labels: hacktoberfest 🎃

#7454 meson -> 0.63.2
  packages/meson.rb
Labels: hacktoberfest 🎃, hacktoberfest-accepted 🎃✔️

#7436 Git w/o musl, install.sh modified to work w/o git in bootstrap.
  install.sh
  packages/crew_profile_base.rb
  packages/git.rb
  packages/glibc.rb
  packages/libcurl.rb
  packages/libidn2.rb
  packages/libpsl.rb
  packages/libssh.rb
  packages/libxml2.rb
Labels: hacktoberfest 🎃

#7479 fix typo in gnucobol
  packages/gnucobol.rb
Labels: bug 🐛, regression ⏪

#7482 lib/downloader: Fix progress bar length on older CrOS terminals
  lib/progress_bar.rb
Labels: bug 🐛, i686

#7125 fix java requirements for Minecraft package
  packages/minecraft.rb
Labels: hacktoberfest 🎃, hacktoberfest-accepted 🎃✔️

#7548 lib/const: Fix `NoMethodError`
  lib/const.rb
Labels: bug 🐛, 🚨🚨 high priority 🚨🚨
