Repository chromebrew/chromebrew, pull requests merged in 2022-01, with the labels that each got.

#6552 fix perl usage in non-self section of package
  packages/info2man.rb
Labels: bug, high priority, installation

#6555 Fix '-j#' regex addition by excluding lines w/ cmake
  lib/const.rb
  lib/package.rb
Labels: bug, high priority

#6565 crew: rescue downloads in non-interactive terminals (such as in container installs)
  lib/const.rb
  lib/downloader.rb
Labels: bug, installation

#6569 Crew: make update of device.json atomic and resilient to running out of disk.
  bin/crew
  lib/const.rb
Labels: enhancement

#6568 install.sh: fix openssl dependency of ruby
  install.sh
Labels: bug, installation

#6635 change logic for setting booleans from env variables
  lib/const.rb
Labels: bug, high priority, regression

#6621 install.sh: Add rsync as a core package
  bin/crew
  install.sh
  lib/const.rb
Labels: cloudready
