Repository chromebrew/chromebrew, pull requests merged in 2022-03, with the labels that each got.

#6849 Fix rsync upgrade breaking crew
  bin/crew
  lib/const.rb
  packages/rsync.rb
Labels: bug

#6869 gh_pages: Fix image glitches in light mode
  css/crew-specific.css
  index.html
Labels: high priority

#6607 libx264 => 5db6aa6
  packages/libx264.rb
Labels: build needed
