Repository chromebrew/chromebrew, pull requests merged in 2022-04, with the labels that each got.

#6580 smbclient => 4.16.0 and tdb => 1.4.6, talloc => 2.3.3, tevent => 0.11.0, ldb => 2.5.0, add perl_json package
  packages/ldb.rb
  packages/perl_json.rb
  packages/smbclient.rb
  packages/talloc.rb
  packages/tdb.rb
  packages/tevent.rb
Labels: build needed

#6266 Default Rubocop linter config for Chromebrew Take 2.5
  .rubocop.yml
  packages/ruby_rubocop.rb
Labels: hacktoberfest

#6962 crew: Fix postinstall, remove extra `!` in `const.rb`
  bin/crew
  lib/const.rb
Labels: high priority

#7013 Add no_patchelf to crew_profile_base, add patchelf to core
  packages/core.rb
  packages/crew_profile_base.rb
Labels: bug, high priority, installation
