Repository chromebrew/chromebrew, pull requests merged in 2023-02, with the labels that each got.

#7928 fix cached zstd git dir extraction
  bin/crew
  lib/const.rb
Labels: bug 🐛, regression ⏪

#7964 Fix broken bootstrap files download
  install.sh
Labels: 🚨🚨 high priority 🚨🚨

#7980 add new sommelier binaries
  packages/sommelier.rb
Labels: 🚨🚨 high priority 🚨🚨

#7985 fix sha256 hash for arm mesa binary
  packages/mesa.rb
Labels: bug 🐛, aarch64, armv7l

#8006 epiphany => 43.1
  packages/epiphany.rb
Labels: build needed 🏗️

#8016 [downloader] Fix error
  lib/downloader.rb
Labels: 🚨🚨 high priority 🚨🚨
