Repository chromebrew/chromebrew, pull requests merged in 2024-02, with the labels that each got.

#9241 Rework installer, change USER_SPACE_ARCH
  install.sh
  lib/const.rb
Labels: 🚨🚨 high priority 🚨🚨, installation 🔻

#9280 fix aarch64 installs, Remove USER_SPACE_ARCH
  bin/crew
  install.sh
  lib/const.rb
Labels: 🚨🚨 high priority 🚨🚨, installation 🔻

#9300 Fix install: Do not run getrealdeps.rb from crew if no_compile_needed is true
  bin/crew
  lib/const.rb
Labels: 🚨🚨 high priority 🚨🚨, installation 🔻, regression ⏪

#9301 Fix install part 2: Add no_compile_needed to all ruby_packages
  packages/ruby_asciidoctor.rb
  packages/ruby_concurrent_ruby.rb
  packages/ruby_docopt.rb
  packages/ruby_mdl.rb
  packages/ruby_rubocop.rb
  packages/ruby_webrick.rb
  packages/ruby_yaml_lint.rb
Labels: 🚨🚨 high priority 🚨🚨, installation 🔻, regression ⏪

#9315 Revert "Miscellaneous crew changes"
  bin/crew
  install.sh
  lib/const.rb
  lib/package.rb
  packages/jdk8.rb
  tests/cycle_test
Labels: regression ⏪

#9342 fixup: don't add path because crew_profile_base should provide it.
  lib/fixup.rb
Labels: regression ⏪
